# Generated by Django 4.1.3 on 2024-06-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_green_oasis_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='GREEN_OASIS_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.DeleteModel(
            name='GREEN_OASIS',
        ),
    ]
