# Generated by Django 4.1.3 on 2024-06-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_green_oasis_en_delete_green_oasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='green_oasis_en',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
