# Generated by Django 4.1.3 on 2024-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_green_oasis_de_green_oasis_pl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRIGHT_SIMPLICITY_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='BRIGHT_SIMPLICITY_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='BRIGHT_SIMPLICITY_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='FUTURE_ON_TOP_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='FUTURE_ON_TOP_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='FUTURE_ON_TOP_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
    ]
