# Generated by Django 4.1.3 on 2024-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bright_simplicity_de_bright_simplicity_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MODERN_TWINS_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='MODERN_TWINS_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='MODERN_TWINS_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='MODERNITY_IN_GLASS_WALLS_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='MODERNITY_IN_GLASS_WALLS_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='MODERNITY_IN_GLASS_WALLS_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='PRIVATE_COSINESS_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='PRIVATE_COSINESS_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='PRIVATE_COSINESS_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='SPACE_FOR_CREATIVITY_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='SPACE_FOR_CREATIVITY_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='SPACE_FOR_CREATIVITY_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='STRICT_ELEGANCE_DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='STRICT_ELEGANCE_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
        migrations.CreateModel(
            name='STRICT_ELEGANCE_PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.TextField(verbose_name='status')),
                ('location', models.TextField(verbose_name='location')),
                ('floorsAndSuites', models.TextField(verbose_name='floorsAndSuites')),
            ],
        ),
    ]
